// Generated by https://quicktype.io

import { Item } from './hn-item';

export interface Ask extends Item {
  by: string;
  descendants: number;
  id: number;
  kids: number[];
  score: number;
  text: string;
  time: number;
  title: string;
  type: 'story';
}
