// Generated by https://quicktype.io

import { Item } from './hn-item';

export interface Comment extends Item {
  by: string;
  id: number;
  kids: number[];
  parent: number;
  text: string;
  time: number;
  type: 'comment';
}
