// Generated by https://quicktype.io

import { Item } from './hn-item';

export interface Job extends Item {
  by: string;
  id: number;
  score: number;
  text: string;
  time: number;
  title: string;
  type: 'job';
  url: string;
}
