// Generated by https://quicktype.io

import { Item } from './hn-item';

export interface Poll extends Item {
  by: string;
  descendants: number;
  id: number;
  kids: number[];
  parts: number[];
  score: number;
  text: string;
  time: number;
  title: string;
  type: 'poll';
}

export interface PollOpt extends Item {
  by: string;
  id: number;
  poll: number;
  score: number;
  text: string;
  time: number;
  type: 'pollopt';
}
