// Generated by https://quicktype.io

import { Item } from './hn-item';

export interface Story extends Item {
  by: string;
  descendants: number;
  id: number;
  kids: number[];
  score: number;
  time: number;
  title: string;
  type: 'story';
  url: string;
}
